export const ADD_TO_CARD_FROM_DETAIL = 'ADD_TO_CARD_FROM_DETAIL';
export const ADD_TO_CARD_FROM_CARD_LIST = 'ADD_TO_CARD_FROM_CARD_LIST';
export const REMOVE_ITEM_FROM_CARD_LIST = 'REMOVE_ITEM_FROM_CARD_LIST';
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';