export const ADMIN_ALL_ORDERs_REQUEST = 'ADMIN_ALL_ORDERs_REQUEST';
export const ADMIN_ALL_ORDERs_SUCCESS = 'ADMIN_ALL_ORDERs_SUCCESS';
export const ADMIN_ALL_ORDERs_FAIL = 'ADMIN_ALL_ORDERs_FAIL';

export const ADMIN_UPDATE_ORDER_REQUEST = 'ADMIN_UPDATE_ORDER_REQUEST';
export const ADMIN_UPDATE_ORDER_SUCCESS = 'ADMIN_UPDATE_ORDER_SUCCESS';
export const ADMIN_UPDATE_ORDER_RESET = 'ADMIN_UPDATE_ORDER_RESET';
export const ADMIN_UPDATE_ORDER_FAIL = 'ADMIN_UPDATE_ORDER_FAIL';

export const ADMIN_DELETE_ORDER_REQUEST = 'ADMIN_DELETE_ORDER_REQUEST';
export const ADMIN_DELETE_ORDER_SUCCESS = 'ADMIN_DELETE_ORDER_SUCCESS';
export const ADMIN_DELETE_ORDER_RESET = 'ADMIN_DELETE_ORDER_RESET';
export const ADMIN_DELETE_ORDER_FAIL = 'ADMIN_DELETE_ORDER_FAIL';

export const CREAT_ORDER_REQUEST = 'CREAT_ORDER_REQUEST';
export const CREAT_ORDER_SUCCESS = 'CREAT_ORDER_SUCCESS';
export const CREAT_ORDER_FAIL = 'CREAT_ORDER_FAIL';

export const ALL_ORDERs_REQUEST = 'ALL_ORDERs_REQUEST';
export const ALL_ORDERs_SUCCESS = 'ALL_ORDERs_SUCCESS';
export const ALL_ORDERs_FAIL = 'ALL_ORDERs_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';