export const ADMIN_ALL_PRODUCTS_REQUEST = 'ADMIN_ALL_PRODUCTS_REQUEST';
export const ADMIN_ALL_PRODUCTS_SUCCESS = 'ADMIN_ALL_PRODUCTS_SUCCESS';
export const ADMIN_ALL_PRODUCTS_FAIL = 'ADMIN_ALL_PRODUCTS_FAIL';

export const NEW_PRODUCT_CREAT_REQUEST = 'NEW_PRODUCT_CREAT_REQUEST';
export const NEW_PRODUCT_CREAT_SUCCESS = 'NEW_PRODUCT_CREAT_SUCCESS';
export const NEW_PRODUCT_CREAT_RESET = 'NEW_PRODUCT_CREAT_RESET';
export const NEW_PRODUCT_CREAT_FAIL = 'NEW_PRODUCT_CREAT_FAIL';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';



export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const NEW_PRODUCT_REVIEW_REQUEST = 'NEW_PRODUCT_REVIEW_REQUEST';
export const NEW_PRODUCT_REVIEW_SUCCESS = 'NEW_PRODUCT_REVIEW_SUCCESS';
export const NEW_PRODUCT_REVIEW_RESET = 'NEW_PRODUCT_REVIEW_RESET';
export const NEW_PRODUCT_REVIEW_FAIL = 'NEW_PRODUCT_REVIEW_FAIL';

export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST';
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS';
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL';

export const DELETE_PRODUCT_REVIEW_REQUEST = 'DELETE_PRODUCT_REVIEW_REQUEST';
export const DELETE_PRODUCT_REVIEW_SUCCESS = 'DELETE_PRODUCT_REVIEW_SUCCESS';
export const DELETE_PRODUCT_REVIEW_RESET = 'DELETE_PRODUCT_REVIEW_RESET';
export const DELETE_PRODUCT_REVIEW_FAIL = 'DELETE_PRODUCT_REVIEW_FAIL';


// not Good  
export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';