module.exports = {
     API_URL: 'http://127.0.0.1:8080/api/v1',
     API_PATH: '/api/v1',
     CURRENCY: '₹',
     CATEGORY: [
          'Appliances',
          'Apps & Games',
          'Arts, Crafts, & Sewing',
          'Automotive Parts & Accessories',
          'Baby',
          'Beauty & Personal Care',
          'Books',
          'CDs & Vinyl',
          'Cell Phones & Accessories',
          'Clothing, Shoes and Jewelry',
          'Collectibles & Fine Art',
          'Computers',
          'Electronics',
          'Garden & Outdoor',
          'Grocery & Gourmet Food',
          'Handmade',
          'Health, Household & Baby Care',
          'Home & Kitchen',
          'Industrial & Scientific',
          'Kindle',
          'Luggage & Travel Gear',
          'Movies & TV',
          'Musical Instruments',
          'Office Products',
          'Pet Supplies',
          'Sports & Outdoors',
          'Tools & Home Improvement',
          'Toys & Games',
          'Video Games'
     ],
     env_texParcent: 0.5,
     env_shippingPrice: 50,
     MATCH_ADMIN: /\/admin\/*/
}